export interface EthnicityOption {
  value: string;
  label: string;
}

export const ETHNICITY_OPTIONS: EthnicityOption[] = [
  { value: "Kinh", label: "Kinh" },
  { value: "Tày", label: "Tày" },
  { value: "Thái", label: "Thái" },
  { value: "Mường", label: "Mường" },
  { value: "Khơ-me", label: "Khơ-me" },
  { value: "Hoa", label: "Hoa" },
  { value: "Nùng", label: "Nùng" },
  { value: "H'Mông", label: "H'Mông" },
  { value: "Dao", label: "Dao" },
  { value: "Gia-rai", label: "Gia-rai" },
  { value: "Ê-đê", label: "Ê-đê" },
  { value: "Ba-na", label: "Ba-na" },
  { value: "Xơ-đăng", label: "Xơ-đăng" },
  { value: "Sán Chay", label: "Sán Chay" },
  { value: "Cơ-ho", label: "Cơ-ho" },
  { value: "Chăm", label: "Chăm" },
  { value: "Sán Dìu", label: "Sán Dìu" },
  { value: "Hrê", label: "Hrê" },
  { value: "Mnông", label: "Mnông" },
  { value: "Ra-glai", label: "Ra-glai" },
  { value: "Xtiêng", label: "Xtiêng" },
  { value: "Bru-Vân Kiều", label: "Bru-Vân Kiều" },
  { value: "Thổ", label: "Thổ" },
  { value: "Giáy", label: "Giáy" },
  { value: "Cơ-tu", label: "Cơ-tu" },
  { value: "Gié-Triêng", label: "Gié-Triêng" },
  { value: "Mạ", label: "Mạ" },
  { value: "Khơ-mú", label: "Khơ-mú" },
  { value: "Co", label: "Co" },
  { value: "Ta-ôi", label: "Ta-ôi" },
  { value: "Chơ-ro", label: "Chơ-ro" },
  { value: "Kháng", label: "Kháng" },
  { value: "Xinh-mun", label: "Xinh-mun" },
  { value: "Hà Nhì", label: "Hà Nhì" },
  { value: "Chu-ru", label: "Chu-ru" },
  { value: "Lào", label: "Lào" },
  { value: "La Chi", label: "La Chi" },
  { value: "La Ha", label: "La Ha" },
  { value: "Phù Lá", label: "Phù Lá" },
  { value: "La Hủ", label: "La Hủ" },
  { value: "Lự", label: "Lự" },
  { value: "Lô Lô", label: "Lô Lô" },
  { value: "Chứt", label: "Chứt" },
  { value: "Mảng", label: "Mảng" },
  { value: "Pà Thẻn", label: "Pà Thẻn" },
  { value: "Co Lao", label: "Co Lao" },
  { value: "Cống", label: "Cống" },
  { value: "Bố Y", label: "Bố Y" },
  { value: "Si La", label: "Si La" },
  { value: "Pu Péo", label: "Pu Péo" },
  { value: "Brâu", label: "Brâu" },
  { value: "Rơ Măm", label: "Rơ Măm" },
  { value: "Ơ Đu", label: "Ơ Đu" },
  { value: "Ngái", label: "Ngái" },
];

